const projects=[
{title:'Style Muse',category:'social',label:'Fashion · Social brand board',image:'style-muse-photography.png',alt:'Style Muse concept brand board with fashion photographs and nine social post designs'},
{title:'Glow Theory',category:'social',label:'Skincare · Social brand board',image:'glow-theory-photography.png',alt:'Glow Theory concept brand board with skincare photographs and nine social post designs'},
{title:'Brew & Bean',category:'social',label:'Café · Social brand board',image:'brew-bean-photography.png',alt:'Brew and Bean concept brand board with café photographs and nine social post designs'},
{title:'Stronger With Sam',category:'social',label:'Fitness · Social brand board',image:'stronger-with-sam-photography.png',alt:'Stronger With Sam concept brand board with fitness photographs and nine social post designs'},
{title:'Pastry Order App',category:'ui',label:'Personal project · Figma UI design',type:'phones'},
{title:'Facebook Page Management',category:'management',label:'Foodtastic · Real project',type:'food'},
{title:'Facebook Page Management',category:'management',label:'Be happy. · Real project',type:'floral'}];
const asset=(file)=>'assets/'+file;
function image(file,alt,cls=''){return `<img src="${asset(file)}" alt="${alt}" class="${cls}" loading="lazy">`}
function artwork(p){if(p.image)return image(p.image,p.alt);if(p.type==='phones')return `<div class="phone-set">${image('pastry-welcome.png','Pastry app welcome screen')}${image('pastry-login.png','Pastry app login screen')}${image('pastry-menu.png','Pastry app menu screen')}</div>`;const kind=p.type==='food'?'food':'floral';return `<div class="case-canvas ${kind}">${image(`facebook-${kind}-board.jpg`,'Facebook page management case study','base')}${image(`facebook-${kind}-profile.png`,'Original Facebook page overview','profile')}${image(`facebook-${kind}-posts.png`,'Original Facebook content and page activity','posts')}</div>`}
const grid=document.querySelector('#project-grid');
projects.forEach((p,i)=>{const article=document.createElement('article');article.className='project';article.dataset.category=p.category;article.innerHTML=`<button aria-label="View ${p.title}, ${p.label}" data-project="${i}"><div class="project-cover">${artwork(p)}<span class="open-label">View project +</span></div><div class="project-meta"><div><h3>${p.title}</h3><p>${p.label}</p></div><span class="project-number">${String(i+1).padStart(2,'0')}</span></div></button>`;grid.append(article)});
let activeFilter='all';document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{activeFilter=button.dataset.filter;document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));let count=0;document.querySelectorAll('.project').forEach(card=>{card.hidden=activeFilter!=='all'&&card.dataset.category!==activeFilter;if(!card.hidden)count++});document.querySelector('#work-count').textContent=count+' project'+(count===1?'':'s')}));
const dialog=document.querySelector('#project-dialog');let activeProject=0;let opener=null;
function showProject(index){activeProject=index;const p=projects[index];document.querySelector('#dialog-title').textContent=p.title;document.querySelector('#dialog-category').textContent=p.label;document.querySelector('#dialog-position').textContent=`${index+1} / ${projects.length}`;let body=artwork(p);if(p.type==='food'||p.type==='floral'){const k=p.type;body+=`<div class="original-images"><h3>Page overview</h3>${image(`facebook-${k}-profile.png`,'Full original Facebook page screenshot')}<h3>Content & page activity</h3>${image(`facebook-${k}-posts.png`,'Full original Facebook content screenshot')}</div>`}document.querySelector('#dialog-body').innerHTML=body;dialog.scrollTop=0}
grid.addEventListener('click',e=>{const button=e.target.closest('[data-project]');if(!button)return;opener=button;showProject(Number(button.dataset.project));dialog.showModal();document.body.classList.add('modal-open')});
function closeProject(){dialog.close()}
document.querySelector('.close-dialog').addEventListener('click',closeProject);dialog.addEventListener('close',()=>{document.body.classList.remove('modal-open');opener?.focus()});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeProject()}});document.querySelector('#previous-project').addEventListener('click',()=>showProject((activeProject-1+projects.length)%projects.length));document.querySelector('#next-project').addEventListener('click',()=>showProject((activeProject+1)%projects.length));dialog.addEventListener('keydown',e=>{if(e.key==='ArrowRight'){e.preventDefault();showProject((activeProject+1)%projects.length)}if(e.key==='ArrowLeft'){e.preventDefault();showProject((activeProject-1+projects.length)%projects.length)}});
const toggle=document.querySelector('.menu-toggle');const nav=document.querySelector('#navigation');function closeMenu(){nav.classList.remove('open');toggle.setAttribute('aria-expanded','false')}toggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open))});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu()});
document.querySelector('#copy-email').addEventListener('click',async()=>{const status=document.querySelector('#copy-status');try{await navigator.clipboard.writeText('magalemae@gmail.com');status.textContent='Email address copied.';document.querySelector('#copy-email').textContent='Copied!';setTimeout(()=>document.querySelector('#copy-email').textContent='Copy email',2500)}catch{status.textContent='Select and copy the email address above, or tap it to open your email app.'}});
